alter table KEYMANAGER_BUILDING add constraint FK_KEYMANAGER_BUILDING_ON_LOCATION foreign key (LOCATION_ID) references KEYMANAGER_LOCATION(ID);
create index IDX_KEYMANAGER_BUILDING_ON_LOCATION on KEYMANAGER_BUILDING (LOCATION_ID);
