alter table KEYMANAGER_KEY add constraint FK_KEYMANAGER_KEY_ON_KEYTYPE foreign key (KEYTYPE_ID) references KEYMANAGER_KEY_TYPE(ID);
create index IDX_KEYMANAGER_KEY_ON_KEYTYPE on KEYMANAGER_KEY (KEYTYPE_ID);
