alter table KEYMANAGER_KEY_ISSUED add constraint FK_KEYMANAGER_KEY_ISSUED_ON_KEY foreign key (KEY_ID) references KEYMANAGER_KEY(ID);
create index IDX_KEYMANAGER_KEY_ISSUED_ON_KEY on KEYMANAGER_KEY_ISSUED (KEY_ID);
