alter table KEYMANAGER_KEY_ISSUED add constraint FK_KEYMANAGER_KEY_ISSUED_ON_KEY_UNIQUE foreign key (KEY_UNIQUE_ID) references KEYMANAGER_KEY_ADD(ID);
create index IDX_KEYMANAGER_KEY_ISSUED_ON_KEY_UNIQUE on KEYMANAGER_KEY_ISSUED (KEY_UNIQUE_ID);
